// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_ACTIVE      ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_ON_HOLD     ProjectStatus = 2
	ProjectStatus_PROJECT_STATUS_COMPLETED   ProjectStatus = 3
	ProjectStatus_PROJECT_STATUS_ARCHIVED    ProjectStatus = 4
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_ACTIVE",
		2: "PROJECT_STATUS_ON_HOLD",
		3: "PROJECT_STATUS_COMPLETED",
		4: "PROJECT_STATUS_ARCHIVED",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_ACTIVE":      1,
		"PROJECT_STATUS_ON_HOLD":     2,
		"PROJECT_STATUS_COMPLETED":   3,
		"PROJECT_STATUS_ARCHIVED":    4,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_BLOCKED     TaskStatus = 3
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_TODO",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_BLOCKED",
		4: "TASK_STATUS_DONE",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_TODO":        1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_BLOCKED":     3,
		"TASK_STATUS_DONE":        4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_MEDIUM      Priority = 2
	Priority_PRIORITY_HIGH        Priority = 3
	Priority_PRIORITY_URGENT      Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_HIGH",
		4: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_MEDIUM":      2,
		"PRIORITY_HIGH":        3,
		"PRIORITY_URGENT":      4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginManifest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author      string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	// Default cron schedule (e.g., "*/15 * * * *" for every 15 minutes)
	Schedule string `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Capabilities this plugin provides
	Capabilities []string `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Configuration schema (JSON Schema format)
	ConfigSchema  string `protobuf:"bytes,7,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginManifest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *PluginManifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetConfigSchema() string {
	if x != nil {
		return x.ConfigSchema
	}
	return ""
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration key-value pairs from user config
	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Directory for plugin state storage
	StateDir string `protobuf:"bytes,2,opt,name=state_dir,json=stateDir,proto3" json:"state_dir,omitempty"`
	// Port for the host gRPC server (for plugin callbacks)
	HostServerPort uint32 `protobuf:"varint,3,opt,name=host_server_port,json=hostServerPort,proto3" json:"host_server_port,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigureRequest) GetStateDir() string {
	if x != nil {
		return x.StateDir
	}
	return ""
}

func (x *ConfigureRequest) GetHostServerPort() uint32 {
	if x != nil {
		return x.HostServerPort
	}
	return 0
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this is a dry run (don't make changes)
	DryRun bool `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Optional parameters passed from CLI
	Params        map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Summary of what was done
	Summary *ExecuteSummary `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// Detailed results
	Results       []*ExecuteResult `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetSummary() *ExecuteSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ExecuteResponse) GetResults() []*ExecuteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExecuteSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemsProcessed int32                  `protobuf:"varint,1,opt,name=items_processed,json=itemsProcessed,proto3" json:"items_processed,omitempty"`
	ItemsImported  int32                  `protobuf:"varint,2,opt,name=items_imported,json=itemsImported,proto3" json:"items_imported,omitempty"`
	ItemsSkipped   int32                  `protobuf:"varint,3,opt,name=items_skipped,json=itemsSkipped,proto3" json:"items_skipped,omitempty"`
	ItemsFailed    int32                  `protobuf:"varint,4,opt,name=items_failed,json=itemsFailed,proto3" json:"items_failed,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteSummary) Reset() {
	*x = ExecuteSummary{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSummary) ProtoMessage() {}

func (x *ExecuteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSummary.ProtoReflect.Descriptor instead.
func (*ExecuteSummary) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteSummary) GetItemsProcessed() int32 {
	if x != nil {
		return x.ItemsProcessed
	}
	return 0
}

func (x *ExecuteSummary) GetItemsImported() int32 {
	if x != nil {
		return x.ItemsImported
	}
	return 0
}

func (x *ExecuteSummary) GetItemsSkipped() int32 {
	if x != nil {
		return x.ItemsSkipped
	}
	return 0
}

func (x *ExecuteSummary) GetItemsFailed() int32 {
	if x != nil {
		return x.ItemsFailed
	}
	return 0
}

func (x *ExecuteSummary) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecuteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "imported", "skipped", "failed"
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecuteResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Area struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Area) Reset() {
	*x = Area{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Area) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Area) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Area) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Area) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Area) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Area) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAreasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreasRequest) Reset() {
	*x = ListAreasRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreasRequest) ProtoMessage() {}

func (x *ListAreasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreasRequest.ProtoReflect.Descriptor instead.
func (*ListAreasRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

type ListAreasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Areas         []*Area                `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAreasResponse) Reset() {
	*x = ListAreasResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreasResponse) ProtoMessage() {}

func (x *ListAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreasResponse.ProtoReflect.Descriptor instead.
func (*ListAreasResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ListAreasResponse) GetAreas() []*Area {
	if x != nil {
		return x.Areas
	}
	return nil
}

type GetAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *GetAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          *Area                  `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAreaResponse) Reset() {
	*x = GetAreaResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaResponse) ProtoMessage() {}

func (x *GetAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaResponse.ProtoReflect.Descriptor instead.
func (*GetAreaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *GetAreaResponse) GetArea() *Area {
	if x != nil {
		return x.Area
	}
	return nil
}

type CreateAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAreaRequest) Reset() {
	*x = CreateAreaRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRequest) ProtoMessage() {}

func (x *CreateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAreaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAreaRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateAreaRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Area          *Area                  `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAreaResponse) Reset() {
	*x = CreateAreaResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaResponse) ProtoMessage() {}

func (x *CreateAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaResponse.ProtoReflect.Descriptor instead.
func (*CreateAreaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAreaResponse) GetArea() *Area {
	if x != nil {
		return x.Area
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AreaId        string                 `protobuf:"bytes,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=reorg.plugin.v1.ProjectStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *Project) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Project) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *Project) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Project) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        string                 `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ListProjectsRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type ListAllProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllProjectsResponse) Reset() {
	*x = ListAllProjectsResponse{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllProjectsResponse) ProtoMessage() {}

func (x *ListAllProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListAllProjectsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ListAllProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *GetProjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AreaId        string                 `protobuf:"bytes,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *CreateProjectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProjectRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *CreateProjectRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateProjectRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AreaId        string                 `protobuf:"bytes,4,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status        TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=reorg.plugin.v1.TaskStatus" json:"status,omitempty"`
	Priority      Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=reorg.plugin.v1.Priority" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Task) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	AreaId        string                 `protobuf:"bytes,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=reorg.plugin.v1.Priority" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateTaskRequest) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *CreateTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ProjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Area          string                 `protobuf:"bytes,3,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContext) Reset() {
	*x = ProjectContext{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContext) ProtoMessage() {}

func (x *ProjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContext.ProtoReflect.Descriptor instead.
func (*ProjectContext) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *ProjectContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectContext) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProjectContext) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type CategorizeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ExistingProjects []*ProjectContext      `protobuf:"bytes,2,rep,name=existing_projects,json=existingProjects,proto3" json:"existing_projects,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CategorizeRequest) Reset() {
	*x = CategorizeRequest{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeRequest) ProtoMessage() {}

func (x *CategorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeRequest.ProtoReflect.Descriptor instead.
func (*CategorizeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *CategorizeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CategorizeRequest) GetExistingProjects() []*ProjectContext {
	if x != nil {
		return x.ExistingProjects
	}
	return nil
}

type CategorizeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Area              string                 `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	AreaConfidence    float64                `protobuf:"fixed64,2,opt,name=area_confidence,json=areaConfidence,proto3" json:"area_confidence,omitempty"`
	ProjectId         string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                         // ID of existing project if matched
	ProjectSuggestion string                 `protobuf:"bytes,4,opt,name=project_suggestion,json=projectSuggestion,proto3" json:"project_suggestion,omitempty"` // Suggested name for new project
	Tags              []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Summary           string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	IsActionable      bool                   `protobuf:"varint,7,opt,name=is_actionable,json=isActionable,proto3" json:"is_actionable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CategorizeResponse) Reset() {
	*x = CategorizeResponse{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeResponse) ProtoMessage() {}

func (x *CategorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeResponse.ProtoReflect.Descriptor instead.
func (*CategorizeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *CategorizeResponse) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *CategorizeResponse) GetAreaConfidence() float64 {
	if x != nil {
		return x.AreaConfidence
	}
	return 0
}

func (x *CategorizeResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CategorizeResponse) GetProjectSuggestion() string {
	if x != nil {
		return x.ProjectSuggestion
	}
	return ""
}

func (x *CategorizeResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CategorizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CategorizeResponse) GetIsActionable() bool {
	if x != nil {
		return x.IsActionable
	}
	return false
}

type ExtractedTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	DueDate       string                 `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractedTask) Reset() {
	*x = ExtractedTask{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedTask) ProtoMessage() {}

func (x *ExtractedTask) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedTask.ProtoReflect.Descriptor instead.
func (*ExtractedTask) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *ExtractedTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtractedTask) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtractedTask) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ExtractedTask) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *ExtractedTask) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ExtractTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTasksRequest) Reset() {
	*x = ExtractTasksRequest{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTasksRequest) ProtoMessage() {}

func (x *ExtractTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTasksRequest.ProtoReflect.Descriptor instead.
func (*ExtractTasksRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *ExtractTasksRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ExtractTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*ExtractedTask       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractTasksResponse) Reset() {
	*x = ExtractTasksResponse{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTasksResponse) ProtoMessage() {}

func (x *ExtractTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTasksResponse.ProtoReflect.Descriptor instead.
func (*ExtractTasksResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *ExtractTasksResponse) GetTasks() []*ExtractedTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *GetStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *GetStateResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetStateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *SetStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetStateRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *SetStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateRequest) Reset() {
	*x = DeleteStateRequest{}
	mi := &file_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateRequest) ProtoMessage() {}

func (x *DeleteStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *DeleteStateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateResponse) Reset() {
	*x = DeleteStateResponse{}
	mi := &file_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateResponse) ProtoMessage() {}

func (x *DeleteStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateResponse.ProtoReflect.Descriptor instead.
func (*DeleteStateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x0freorg.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\xdd\x01\n" +
	"\x0ePluginManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12#\n" +
	"\rconfig_schema\x18\a \x01(\tR\fconfigSchema\"\xdb\x01\n" +
	"\x10ConfigureRequest\x12E\n" +
	"\x06config\x18\x01 \x03(\v2-.reorg.plugin.v1.ConfigureRequest.ConfigEntryR\x06config\x12\x1b\n" +
	"\tstate_dir\x18\x02 \x01(\tR\bstateDir\x12(\n" +
	"\x10host_server_port\x18\x03 \x01(\rR\x0ehostServerPort\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x11ConfigureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa9\x01\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\x12C\n" +
	"\x06params\x18\x02 \x03(\v2+.reorg.plugin.v1.ExecuteRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x129\n" +
	"\asummary\x18\x03 \x01(\v2\x1f.reorg.plugin.v1.ExecuteSummaryR\asummary\x128\n" +
	"\aresults\x18\x04 \x03(\v2\x1e.reorg.plugin.v1.ExecuteResultR\aresults\"\xc2\x01\n" +
	"\x0eExecuteSummary\x12'\n" +
	"\x0fitems_processed\x18\x01 \x01(\x05R\x0eitemsProcessed\x12%\n" +
	"\x0eitems_imported\x18\x02 \x01(\x05R\ritemsImported\x12#\n" +
	"\ritems_skipped\x18\x03 \x01(\x05R\fitemsSkipped\x12!\n" +
	"\fitems_failed\x18\x04 \x01(\x05R\vitemsFailed\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xec\x01\n" +
	"\rExecuteResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12H\n" +
	"\bmetadata\x18\x05 \x03(\v2,.reorg.plugin.v1.ExecuteResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x04Area\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x12\n" +
	"\x10ListAreasRequest\"@\n" +
	"\x11ListAreasResponse\x12+\n" +
	"\x05areas\x18\x01 \x03(\v2\x15.reorg.plugin.v1.AreaR\x05areas\" \n" +
	"\x0eGetAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetAreaResponse\x12)\n" +
	"\x04area\x18\x01 \x01(\v2\x15.reorg.plugin.v1.AreaR\x04area\"W\n" +
	"\x11CreateAreaRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"?\n" +
	"\x12CreateAreaResponse\x12)\n" +
	"\x04area\x18\x01 \x01(\v2\x15.reorg.plugin.v1.AreaR\x04area\"\xdb\x02\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\aarea_id\x18\x03 \x01(\tR\x06areaId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x126\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1e.reorg.plugin.v1.ProjectStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x125\n" +
	"\bdue_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\".\n" +
	"\x13ListProjectsRequest\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\tR\x06areaId\"L\n" +
	"\x14ListProjectsResponse\x124\n" +
	"\bprojects\x18\x01 \x03(\v2\x18.reorg.plugin.v1.ProjectR\bprojects\"O\n" +
	"\x17ListAllProjectsResponse\x124\n" +
	"\bprojects\x18\x01 \x03(\v2\x18.reorg.plugin.v1.ProjectR\bprojects\"#\n" +
	"\x11GetProjectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12GetProjectResponse\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.reorg.plugin.v1.ProjectR\aproject\"s\n" +
	"\x14CreateProjectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x17\n" +
	"\aarea_id\x18\x02 \x01(\tR\x06areaId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"K\n" +
	"\x15CreateProjectResponse\x122\n" +
	"\aproject\x18\x01 \x01(\v2\x18.reorg.plugin.v1.ProjectR\aproject\"\xab\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x17\n" +
	"\aarea_id\x18\x04 \x01(\tR\x06areaId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.reorg.plugin.v1.TaskStatusR\x06status\x125\n" +
	"\bpriority\x18\a \x01(\x0e2\x19.reorg.plugin.v1.PriorityR\bpriority\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x125\n" +
	"\bdue_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"1\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"@\n" +
	"\x11ListTasksResponse\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.reorg.plugin.v1.TaskR\x05tasks\"\xc6\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\aarea_id\x18\x03 \x01(\tR\x06areaId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x125\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x19.reorg.plugin.v1.PriorityR\bpriority\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"?\n" +
	"\x12CreateTaskResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.reorg.plugin.v1.TaskR\x04task\"J\n" +
	"\x0eProjectContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04area\x18\x03 \x01(\tR\x04area\"{\n" +
	"\x11CategorizeRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12L\n" +
	"\x11existing_projects\x18\x02 \x03(\v2\x1f.reorg.plugin.v1.ProjectContextR\x10existingProjects\"\xf2\x01\n" +
	"\x12CategorizeResponse\x12\x12\n" +
	"\x04area\x18\x01 \x01(\tR\x04area\x12'\n" +
	"\x0farea_confidence\x18\x02 \x01(\x01R\x0eareaConfidence\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12-\n" +
	"\x12project_suggestion\x18\x04 \x01(\tR\x11projectSuggestion\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12#\n" +
	"\ris_actionable\x18\a \x01(\bR\fisActionable\"\x92\x01\n" +
	"\rExtractedTask\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"/\n" +
	"\x13ExtractTasksRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"L\n" +
	"\x14ExtractTasksResponse\x124\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1e.reorg.plugin.v1.ExtractedTaskR\x05tasks\"#\n" +
	"\x0fGetStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\x10GetStateResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"9\n" +
	"\x0fSetStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\",\n" +
	"\x10SetStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x12DeleteStateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"/\n" +
	"\x13DeleteStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xa1\x01\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROJECT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16PROJECT_STATUS_ON_HOLD\x10\x02\x12\x1c\n" +
	"\x18PROJECT_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17PROJECT_STATUS_ARCHIVED\x10\x04*\xa6\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_BLOCKED\x10\x03\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05*s\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x03\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x042\xb3\x02\n" +
	"\vReorgPlugin\x12F\n" +
	"\vGetManifest\x12\x16.reorg.plugin.v1.Empty\x1a\x1f.reorg.plugin.v1.PluginManifest\x12R\n" +
	"\tConfigure\x12!.reorg.plugin.v1.ConfigureRequest\x1a\".reorg.plugin.v1.ConfigureResponse\x12L\n" +
	"\aExecute\x12\x1f.reorg.plugin.v1.ExecuteRequest\x1a .reorg.plugin.v1.ExecuteResponse\x12:\n" +
	"\bShutdown\x12\x16.reorg.plugin.v1.Empty\x1a\x16.reorg.plugin.v1.Empty2\xd3\t\n" +
	"\tReorgHost\x12R\n" +
	"\tListAreas\x12!.reorg.plugin.v1.ListAreasRequest\x1a\".reorg.plugin.v1.ListAreasResponse\x12L\n" +
	"\aGetArea\x12\x1f.reorg.plugin.v1.GetAreaRequest\x1a .reorg.plugin.v1.GetAreaResponse\x12U\n" +
	"\n" +
	"CreateArea\x12\".reorg.plugin.v1.CreateAreaRequest\x1a#.reorg.plugin.v1.CreateAreaResponse\x12[\n" +
	"\fListProjects\x12$.reorg.plugin.v1.ListProjectsRequest\x1a%.reorg.plugin.v1.ListProjectsResponse\x12S\n" +
	"\x0fListAllProjects\x12\x16.reorg.plugin.v1.Empty\x1a(.reorg.plugin.v1.ListAllProjectsResponse\x12U\n" +
	"\n" +
	"GetProject\x12\".reorg.plugin.v1.GetProjectRequest\x1a#.reorg.plugin.v1.GetProjectResponse\x12^\n" +
	"\rCreateProject\x12%.reorg.plugin.v1.CreateProjectRequest\x1a&.reorg.plugin.v1.CreateProjectResponse\x12R\n" +
	"\tListTasks\x12!.reorg.plugin.v1.ListTasksRequest\x1a\".reorg.plugin.v1.ListTasksResponse\x12U\n" +
	"\n" +
	"CreateTask\x12\".reorg.plugin.v1.CreateTaskRequest\x1a#.reorg.plugin.v1.CreateTaskResponse\x12`\n" +
	"\x15CategorizeWithContext\x12\".reorg.plugin.v1.CategorizeRequest\x1a#.reorg.plugin.v1.CategorizeResponse\x12[\n" +
	"\fExtractTasks\x12$.reorg.plugin.v1.ExtractTasksRequest\x1a%.reorg.plugin.v1.ExtractTasksResponse\x12O\n" +
	"\bGetState\x12 .reorg.plugin.v1.GetStateRequest\x1a!.reorg.plugin.v1.GetStateResponse\x12O\n" +
	"\bSetState\x12 .reorg.plugin.v1.SetStateRequest\x1a!.reorg.plugin.v1.SetStateResponse\x12X\n" +
	"\vDeleteState\x12#.reorg.plugin.v1.DeleteStateRequest\x1a$.reorg.plugin.v1.DeleteStateResponseB/Z-github.com/ihavespoons/reorg/pkg/plugin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_plugin_proto_goTypes = []any{
	(ProjectStatus)(0),              // 0: reorg.plugin.v1.ProjectStatus
	(TaskStatus)(0),                 // 1: reorg.plugin.v1.TaskStatus
	(Priority)(0),                   // 2: reorg.plugin.v1.Priority
	(*Empty)(nil),                   // 3: reorg.plugin.v1.Empty
	(*PluginManifest)(nil),          // 4: reorg.plugin.v1.PluginManifest
	(*ConfigureRequest)(nil),        // 5: reorg.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),       // 6: reorg.plugin.v1.ConfigureResponse
	(*ExecuteRequest)(nil),          // 7: reorg.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),         // 8: reorg.plugin.v1.ExecuteResponse
	(*ExecuteSummary)(nil),          // 9: reorg.plugin.v1.ExecuteSummary
	(*ExecuteResult)(nil),           // 10: reorg.plugin.v1.ExecuteResult
	(*Area)(nil),                    // 11: reorg.plugin.v1.Area
	(*ListAreasRequest)(nil),        // 12: reorg.plugin.v1.ListAreasRequest
	(*ListAreasResponse)(nil),       // 13: reorg.plugin.v1.ListAreasResponse
	(*GetAreaRequest)(nil),          // 14: reorg.plugin.v1.GetAreaRequest
	(*GetAreaResponse)(nil),         // 15: reorg.plugin.v1.GetAreaResponse
	(*CreateAreaRequest)(nil),       // 16: reorg.plugin.v1.CreateAreaRequest
	(*CreateAreaResponse)(nil),      // 17: reorg.plugin.v1.CreateAreaResponse
	(*Project)(nil),                 // 18: reorg.plugin.v1.Project
	(*ListProjectsRequest)(nil),     // 19: reorg.plugin.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),    // 20: reorg.plugin.v1.ListProjectsResponse
	(*ListAllProjectsResponse)(nil), // 21: reorg.plugin.v1.ListAllProjectsResponse
	(*GetProjectRequest)(nil),       // 22: reorg.plugin.v1.GetProjectRequest
	(*GetProjectResponse)(nil),      // 23: reorg.plugin.v1.GetProjectResponse
	(*CreateProjectRequest)(nil),    // 24: reorg.plugin.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),   // 25: reorg.plugin.v1.CreateProjectResponse
	(*Task)(nil),                    // 26: reorg.plugin.v1.Task
	(*ListTasksRequest)(nil),        // 27: reorg.plugin.v1.ListTasksRequest
	(*ListTasksResponse)(nil),       // 28: reorg.plugin.v1.ListTasksResponse
	(*CreateTaskRequest)(nil),       // 29: reorg.plugin.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),      // 30: reorg.plugin.v1.CreateTaskResponse
	(*ProjectContext)(nil),          // 31: reorg.plugin.v1.ProjectContext
	(*CategorizeRequest)(nil),       // 32: reorg.plugin.v1.CategorizeRequest
	(*CategorizeResponse)(nil),      // 33: reorg.plugin.v1.CategorizeResponse
	(*ExtractedTask)(nil),           // 34: reorg.plugin.v1.ExtractedTask
	(*ExtractTasksRequest)(nil),     // 35: reorg.plugin.v1.ExtractTasksRequest
	(*ExtractTasksResponse)(nil),    // 36: reorg.plugin.v1.ExtractTasksResponse
	(*GetStateRequest)(nil),         // 37: reorg.plugin.v1.GetStateRequest
	(*GetStateResponse)(nil),        // 38: reorg.plugin.v1.GetStateResponse
	(*SetStateRequest)(nil),         // 39: reorg.plugin.v1.SetStateRequest
	(*SetStateResponse)(nil),        // 40: reorg.plugin.v1.SetStateResponse
	(*DeleteStateRequest)(nil),      // 41: reorg.plugin.v1.DeleteStateRequest
	(*DeleteStateResponse)(nil),     // 42: reorg.plugin.v1.DeleteStateResponse
	nil,                             // 43: reorg.plugin.v1.ConfigureRequest.ConfigEntry
	nil,                             // 44: reorg.plugin.v1.ExecuteRequest.ParamsEntry
	nil,                             // 45: reorg.plugin.v1.ExecuteResult.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 46: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	43, // 0: reorg.plugin.v1.ConfigureRequest.config:type_name -> reorg.plugin.v1.ConfigureRequest.ConfigEntry
	44, // 1: reorg.plugin.v1.ExecuteRequest.params:type_name -> reorg.plugin.v1.ExecuteRequest.ParamsEntry
	9,  // 2: reorg.plugin.v1.ExecuteResponse.summary:type_name -> reorg.plugin.v1.ExecuteSummary
	10, // 3: reorg.plugin.v1.ExecuteResponse.results:type_name -> reorg.plugin.v1.ExecuteResult
	45, // 4: reorg.plugin.v1.ExecuteResult.metadata:type_name -> reorg.plugin.v1.ExecuteResult.MetadataEntry
	46, // 5: reorg.plugin.v1.Area.created_at:type_name -> google.protobuf.Timestamp
	46, // 6: reorg.plugin.v1.Area.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: reorg.plugin.v1.ListAreasResponse.areas:type_name -> reorg.plugin.v1.Area
	11, // 8: reorg.plugin.v1.GetAreaResponse.area:type_name -> reorg.plugin.v1.Area
	11, // 9: reorg.plugin.v1.CreateAreaResponse.area:type_name -> reorg.plugin.v1.Area
	0,  // 10: reorg.plugin.v1.Project.status:type_name -> reorg.plugin.v1.ProjectStatus
	46, // 11: reorg.plugin.v1.Project.due_date:type_name -> google.protobuf.Timestamp
	46, // 12: reorg.plugin.v1.Project.created_at:type_name -> google.protobuf.Timestamp
	46, // 13: reorg.plugin.v1.Project.updated_at:type_name -> google.protobuf.Timestamp
	18, // 14: reorg.plugin.v1.ListProjectsResponse.projects:type_name -> reorg.plugin.v1.Project
	18, // 15: reorg.plugin.v1.ListAllProjectsResponse.projects:type_name -> reorg.plugin.v1.Project
	18, // 16: reorg.plugin.v1.GetProjectResponse.project:type_name -> reorg.plugin.v1.Project
	18, // 17: reorg.plugin.v1.CreateProjectResponse.project:type_name -> reorg.plugin.v1.Project
	1,  // 18: reorg.plugin.v1.Task.status:type_name -> reorg.plugin.v1.TaskStatus
	2,  // 19: reorg.plugin.v1.Task.priority:type_name -> reorg.plugin.v1.Priority
	46, // 20: reorg.plugin.v1.Task.due_date:type_name -> google.protobuf.Timestamp
	46, // 21: reorg.plugin.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	46, // 22: reorg.plugin.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	26, // 23: reorg.plugin.v1.ListTasksResponse.tasks:type_name -> reorg.plugin.v1.Task
	2,  // 24: reorg.plugin.v1.CreateTaskRequest.priority:type_name -> reorg.plugin.v1.Priority
	26, // 25: reorg.plugin.v1.CreateTaskResponse.task:type_name -> reorg.plugin.v1.Task
	31, // 26: reorg.plugin.v1.CategorizeRequest.existing_projects:type_name -> reorg.plugin.v1.ProjectContext
	34, // 27: reorg.plugin.v1.ExtractTasksResponse.tasks:type_name -> reorg.plugin.v1.ExtractedTask
	3,  // 28: reorg.plugin.v1.ReorgPlugin.GetManifest:input_type -> reorg.plugin.v1.Empty
	5,  // 29: reorg.plugin.v1.ReorgPlugin.Configure:input_type -> reorg.plugin.v1.ConfigureRequest
	7,  // 30: reorg.plugin.v1.ReorgPlugin.Execute:input_type -> reorg.plugin.v1.ExecuteRequest
	3,  // 31: reorg.plugin.v1.ReorgPlugin.Shutdown:input_type -> reorg.plugin.v1.Empty
	12, // 32: reorg.plugin.v1.ReorgHost.ListAreas:input_type -> reorg.plugin.v1.ListAreasRequest
	14, // 33: reorg.plugin.v1.ReorgHost.GetArea:input_type -> reorg.plugin.v1.GetAreaRequest
	16, // 34: reorg.plugin.v1.ReorgHost.CreateArea:input_type -> reorg.plugin.v1.CreateAreaRequest
	19, // 35: reorg.plugin.v1.ReorgHost.ListProjects:input_type -> reorg.plugin.v1.ListProjectsRequest
	3,  // 36: reorg.plugin.v1.ReorgHost.ListAllProjects:input_type -> reorg.plugin.v1.Empty
	22, // 37: reorg.plugin.v1.ReorgHost.GetProject:input_type -> reorg.plugin.v1.GetProjectRequest
	24, // 38: reorg.plugin.v1.ReorgHost.CreateProject:input_type -> reorg.plugin.v1.CreateProjectRequest
	27, // 39: reorg.plugin.v1.ReorgHost.ListTasks:input_type -> reorg.plugin.v1.ListTasksRequest
	29, // 40: reorg.plugin.v1.ReorgHost.CreateTask:input_type -> reorg.plugin.v1.CreateTaskRequest
	32, // 41: reorg.plugin.v1.ReorgHost.CategorizeWithContext:input_type -> reorg.plugin.v1.CategorizeRequest
	35, // 42: reorg.plugin.v1.ReorgHost.ExtractTasks:input_type -> reorg.plugin.v1.ExtractTasksRequest
	37, // 43: reorg.plugin.v1.ReorgHost.GetState:input_type -> reorg.plugin.v1.GetStateRequest
	39, // 44: reorg.plugin.v1.ReorgHost.SetState:input_type -> reorg.plugin.v1.SetStateRequest
	41, // 45: reorg.plugin.v1.ReorgHost.DeleteState:input_type -> reorg.plugin.v1.DeleteStateRequest
	4,  // 46: reorg.plugin.v1.ReorgPlugin.GetManifest:output_type -> reorg.plugin.v1.PluginManifest
	6,  // 47: reorg.plugin.v1.ReorgPlugin.Configure:output_type -> reorg.plugin.v1.ConfigureResponse
	8,  // 48: reorg.plugin.v1.ReorgPlugin.Execute:output_type -> reorg.plugin.v1.ExecuteResponse
	3,  // 49: reorg.plugin.v1.ReorgPlugin.Shutdown:output_type -> reorg.plugin.v1.Empty
	13, // 50: reorg.plugin.v1.ReorgHost.ListAreas:output_type -> reorg.plugin.v1.ListAreasResponse
	15, // 51: reorg.plugin.v1.ReorgHost.GetArea:output_type -> reorg.plugin.v1.GetAreaResponse
	17, // 52: reorg.plugin.v1.ReorgHost.CreateArea:output_type -> reorg.plugin.v1.CreateAreaResponse
	20, // 53: reorg.plugin.v1.ReorgHost.ListProjects:output_type -> reorg.plugin.v1.ListProjectsResponse
	21, // 54: reorg.plugin.v1.ReorgHost.ListAllProjects:output_type -> reorg.plugin.v1.ListAllProjectsResponse
	23, // 55: reorg.plugin.v1.ReorgHost.GetProject:output_type -> reorg.plugin.v1.GetProjectResponse
	25, // 56: reorg.plugin.v1.ReorgHost.CreateProject:output_type -> reorg.plugin.v1.CreateProjectResponse
	28, // 57: reorg.plugin.v1.ReorgHost.ListTasks:output_type -> reorg.plugin.v1.ListTasksResponse
	30, // 58: reorg.plugin.v1.ReorgHost.CreateTask:output_type -> reorg.plugin.v1.CreateTaskResponse
	33, // 59: reorg.plugin.v1.ReorgHost.CategorizeWithContext:output_type -> reorg.plugin.v1.CategorizeResponse
	36, // 60: reorg.plugin.v1.ReorgHost.ExtractTasks:output_type -> reorg.plugin.v1.ExtractTasksResponse
	38, // 61: reorg.plugin.v1.ReorgHost.GetState:output_type -> reorg.plugin.v1.GetStateResponse
	40, // 62: reorg.plugin.v1.ReorgHost.SetState:output_type -> reorg.plugin.v1.SetStateResponse
	42, // 63: reorg.plugin.v1.ReorgHost.DeleteState:output_type -> reorg.plugin.v1.DeleteStateResponse
	46, // [46:64] is the sub-list for method output_type
	28, // [28:46] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
