// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReorgPlugin_GetManifest_FullMethodName = "/reorg.plugin.v1.ReorgPlugin/GetManifest"
	ReorgPlugin_Configure_FullMethodName   = "/reorg.plugin.v1.ReorgPlugin/Configure"
	ReorgPlugin_Execute_FullMethodName     = "/reorg.plugin.v1.ReorgPlugin/Execute"
	ReorgPlugin_Shutdown_FullMethodName    = "/reorg.plugin.v1.ReorgPlugin/Shutdown"
)

// ReorgPluginClient is the client API for ReorgPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReorgPluginClient interface {
	// GetManifest returns the plugin's metadata and capabilities
	GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginManifest, error)
	// Configure sets up the plugin with host-provided configuration
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Execute runs the plugin's main logic
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Shutdown gracefully stops the plugin
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type reorgPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewReorgPluginClient(cc grpc.ClientConnInterface) ReorgPluginClient {
	return &reorgPluginClient{cc}
}

func (c *reorgPluginClient) GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, ReorgPlugin_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgPluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, ReorgPlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ReorgPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgPluginClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReorgPlugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReorgPluginServer is the server API for ReorgPlugin service.
// All implementations must embed UnimplementedReorgPluginServer
// for forward compatibility.
type ReorgPluginServer interface {
	// GetManifest returns the plugin's metadata and capabilities
	GetManifest(context.Context, *Empty) (*PluginManifest, error)
	// Configure sets up the plugin with host-provided configuration
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Execute runs the plugin's main logic
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Shutdown gracefully stops the plugin
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedReorgPluginServer()
}

// UnimplementedReorgPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReorgPluginServer struct{}

func (UnimplementedReorgPluginServer) GetManifest(context.Context, *Empty) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedReorgPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedReorgPluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedReorgPluginServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedReorgPluginServer) mustEmbedUnimplementedReorgPluginServer() {}
func (UnimplementedReorgPluginServer) testEmbeddedByValue()                     {}

// UnsafeReorgPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReorgPluginServer will
// result in compilation errors.
type UnsafeReorgPluginServer interface {
	mustEmbedUnimplementedReorgPluginServer()
}

func RegisterReorgPluginServer(s grpc.ServiceRegistrar, srv ReorgPluginServer) {
	// If the following call panics, it indicates UnimplementedReorgPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReorgPlugin_ServiceDesc, srv)
}

func _ReorgPlugin_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgPluginServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgPlugin_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgPluginServer).GetManifest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgPluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgPluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgPlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgPluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgPlugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgPluginServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ReorgPlugin_ServiceDesc is the grpc.ServiceDesc for ReorgPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReorgPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reorg.plugin.v1.ReorgPlugin",
	HandlerType: (*ReorgPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _ReorgPlugin_GetManifest_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ReorgPlugin_Configure_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ReorgPlugin_Execute_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ReorgPlugin_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	ReorgHost_ListAreas_FullMethodName             = "/reorg.plugin.v1.ReorgHost/ListAreas"
	ReorgHost_GetArea_FullMethodName               = "/reorg.plugin.v1.ReorgHost/GetArea"
	ReorgHost_CreateArea_FullMethodName            = "/reorg.plugin.v1.ReorgHost/CreateArea"
	ReorgHost_ListProjects_FullMethodName          = "/reorg.plugin.v1.ReorgHost/ListProjects"
	ReorgHost_ListAllProjects_FullMethodName       = "/reorg.plugin.v1.ReorgHost/ListAllProjects"
	ReorgHost_GetProject_FullMethodName            = "/reorg.plugin.v1.ReorgHost/GetProject"
	ReorgHost_CreateProject_FullMethodName         = "/reorg.plugin.v1.ReorgHost/CreateProject"
	ReorgHost_ListTasks_FullMethodName             = "/reorg.plugin.v1.ReorgHost/ListTasks"
	ReorgHost_CreateTask_FullMethodName            = "/reorg.plugin.v1.ReorgHost/CreateTask"
	ReorgHost_CategorizeWithContext_FullMethodName = "/reorg.plugin.v1.ReorgHost/CategorizeWithContext"
	ReorgHost_ExtractTasks_FullMethodName          = "/reorg.plugin.v1.ReorgHost/ExtractTasks"
	ReorgHost_GetState_FullMethodName              = "/reorg.plugin.v1.ReorgHost/GetState"
	ReorgHost_SetState_FullMethodName              = "/reorg.plugin.v1.ReorgHost/SetState"
	ReorgHost_DeleteState_FullMethodName           = "/reorg.plugin.v1.ReorgHost/DeleteState"
)

// ReorgHostClient is the client API for ReorgHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReorgHostClient interface {
	// Area operations
	ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasResponse, error)
	GetArea(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*GetAreaResponse, error)
	CreateArea(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*CreateAreaResponse, error)
	// Project operations
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	ListAllProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllProjectsResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	// Task operations
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// LLM operations (proxied through host for centralized API key management)
	CategorizeWithContext(ctx context.Context, in *CategorizeRequest, opts ...grpc.CallOption) (*CategorizeResponse, error)
	ExtractTasks(ctx context.Context, in *ExtractTasksRequest, opts ...grpc.CallOption) (*ExtractTasksResponse, error)
	// State persistence (per-plugin state storage)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error)
	DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*DeleteStateResponse, error)
}

type reorgHostClient struct {
	cc grpc.ClientConnInterface
}

func NewReorgHostClient(cc grpc.ClientConnInterface) ReorgHostClient {
	return &reorgHostClient{cc}
}

func (c *reorgHostClient) ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreasResponse)
	err := c.cc.Invoke(ctx, ReorgHost_ListAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) GetArea(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*GetAreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAreaResponse)
	err := c.cc.Invoke(ctx, ReorgHost_GetArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) CreateArea(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*CreateAreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAreaResponse)
	err := c.cc.Invoke(ctx, ReorgHost_CreateArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, ReorgHost_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) ListAllProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAllProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllProjectsResponse)
	err := c.cc.Invoke(ctx, ReorgHost_ListAllProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, ReorgHost_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, ReorgHost_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ReorgHost_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, ReorgHost_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) CategorizeWithContext(ctx context.Context, in *CategorizeRequest, opts ...grpc.CallOption) (*CategorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategorizeResponse)
	err := c.cc.Invoke(ctx, ReorgHost_CategorizeWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) ExtractTasks(ctx context.Context, in *ExtractTasksRequest, opts ...grpc.CallOption) (*ExtractTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractTasksResponse)
	err := c.cc.Invoke(ctx, ReorgHost_ExtractTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, ReorgHost_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStateResponse)
	err := c.cc.Invoke(ctx, ReorgHost_SetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reorgHostClient) DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*DeleteStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStateResponse)
	err := c.cc.Invoke(ctx, ReorgHost_DeleteState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReorgHostServer is the server API for ReorgHost service.
// All implementations must embed UnimplementedReorgHostServer
// for forward compatibility.
type ReorgHostServer interface {
	// Area operations
	ListAreas(context.Context, *ListAreasRequest) (*ListAreasResponse, error)
	GetArea(context.Context, *GetAreaRequest) (*GetAreaResponse, error)
	CreateArea(context.Context, *CreateAreaRequest) (*CreateAreaResponse, error)
	// Project operations
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	ListAllProjects(context.Context, *Empty) (*ListAllProjectsResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	// Task operations
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// LLM operations (proxied through host for centralized API key management)
	CategorizeWithContext(context.Context, *CategorizeRequest) (*CategorizeResponse, error)
	ExtractTasks(context.Context, *ExtractTasksRequest) (*ExtractTasksResponse, error)
	// State persistence (per-plugin state storage)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	SetState(context.Context, *SetStateRequest) (*SetStateResponse, error)
	DeleteState(context.Context, *DeleteStateRequest) (*DeleteStateResponse, error)
	mustEmbedUnimplementedReorgHostServer()
}

// UnimplementedReorgHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReorgHostServer struct{}

func (UnimplementedReorgHostServer) ListAreas(context.Context, *ListAreasRequest) (*ListAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreas not implemented")
}
func (UnimplementedReorgHostServer) GetArea(context.Context, *GetAreaRequest) (*GetAreaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArea not implemented")
}
func (UnimplementedReorgHostServer) CreateArea(context.Context, *CreateAreaRequest) (*CreateAreaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArea not implemented")
}
func (UnimplementedReorgHostServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedReorgHostServer) ListAllProjects(context.Context, *Empty) (*ListAllProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllProjects not implemented")
}
func (UnimplementedReorgHostServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedReorgHostServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedReorgHostServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedReorgHostServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedReorgHostServer) CategorizeWithContext(context.Context, *CategorizeRequest) (*CategorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CategorizeWithContext not implemented")
}
func (UnimplementedReorgHostServer) ExtractTasks(context.Context, *ExtractTasksRequest) (*ExtractTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractTasks not implemented")
}
func (UnimplementedReorgHostServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedReorgHostServer) SetState(context.Context, *SetStateRequest) (*SetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedReorgHostServer) DeleteState(context.Context, *DeleteStateRequest) (*DeleteStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteState not implemented")
}
func (UnimplementedReorgHostServer) mustEmbedUnimplementedReorgHostServer() {}
func (UnimplementedReorgHostServer) testEmbeddedByValue()                   {}

// UnsafeReorgHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReorgHostServer will
// result in compilation errors.
type UnsafeReorgHostServer interface {
	mustEmbedUnimplementedReorgHostServer()
}

func RegisterReorgHostServer(s grpc.ServiceRegistrar, srv ReorgHostServer) {
	// If the following call panics, it indicates UnimplementedReorgHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReorgHost_ServiceDesc, srv)
}

func _ReorgHost_ListAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).ListAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_ListAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).ListAreas(ctx, req.(*ListAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_GetArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).GetArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_GetArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).GetArea(ctx, req.(*GetAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_CreateArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).CreateArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_CreateArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).CreateArea(ctx, req.(*CreateAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_ListAllProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).ListAllProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_ListAllProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).ListAllProjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_CategorizeWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).CategorizeWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_CategorizeWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).CategorizeWithContext(ctx, req.(*CategorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_ExtractTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).ExtractTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_ExtractTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).ExtractTasks(ctx, req.(*ExtractTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_SetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReorgHost_DeleteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReorgHostServer).DeleteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReorgHost_DeleteState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReorgHostServer).DeleteState(ctx, req.(*DeleteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReorgHost_ServiceDesc is the grpc.ServiceDesc for ReorgHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReorgHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reorg.plugin.v1.ReorgHost",
	HandlerType: (*ReorgHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAreas",
			Handler:    _ReorgHost_ListAreas_Handler,
		},
		{
			MethodName: "GetArea",
			Handler:    _ReorgHost_GetArea_Handler,
		},
		{
			MethodName: "CreateArea",
			Handler:    _ReorgHost_CreateArea_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _ReorgHost_ListProjects_Handler,
		},
		{
			MethodName: "ListAllProjects",
			Handler:    _ReorgHost_ListAllProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ReorgHost_GetProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _ReorgHost_CreateProject_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ReorgHost_ListTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _ReorgHost_CreateTask_Handler,
		},
		{
			MethodName: "CategorizeWithContext",
			Handler:    _ReorgHost_CategorizeWithContext_Handler,
		},
		{
			MethodName: "ExtractTasks",
			Handler:    _ReorgHost_ExtractTasks_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ReorgHost_GetState_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _ReorgHost_SetState_Handler,
		},
		{
			MethodName: "DeleteState",
			Handler:    _ReorgHost_DeleteState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
